version: '3.7'
services:
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: moneytransfer
      POSTGRES_USER: money
      POSTGRES_PASSWORD: transfer
