db:
  driverClassName: "org.postgresql.Driver"
  dataSourceUser: "money"
  dataSourcePassword: "transfer"
  jdbcUrl: "jdbc:postgresql://127.0.0.1:5432/moneytransfer"
  maxLifetime: 900000
  connectionTimeout: 30000
  idleTimeout: 300000
  maximumPoolSize: 50
  minimumIdle: 5
  poolName: mt
  autoCommit: true
  leakDetectionThreshold: 20000