/*
 * This file is generated by jOOQ.
 */
package practice.money.transfer.persistence.tables.references


import practice.money.transfer.persistence.tables.Account



/**
 * The table <code>public.account</code>.
 */
val ACCOUNT: Account = Account.ACCOUNT
